### ISSUE TITLE
The private key not yet shared

### ISSUE THREAD

**Issue by studentofcoding** [jabardigitalservice/pikobar-jabarprov-go-id#1]
![image](https://user-images.githubusercontent.com/20473526/77142480-cd576080-6ab2-11ea-81d5-31af77a8c452.png)

Apparently the private key on env not yet shared, therefore "TypeError, Cannot read property 'replace' of undefined" appear

**Comment by aldidoanta** [comment]
Hello, thanks for reporting the issue :pray: . Currently we have not provisioned a Firebase project for dev/staging purposes. For now, you can set up your own Firebase project for the env variables.

We have not created a technical documentation about this repo (Firestore collection structure etc.). We will update this repo as soon as it's ready.

**Comment by aldidoanta** [comment]
Hi @studentofcoding. If you are still interested in contributing, please take a look at the updated [README.md](https://github.com/jabardigitalservice/pikobar-jabarprov-go-id/blob/master/README.md)
