### ISSUE TITLE
Share via Facebook tidak muncul judul berita dan excerpt contentnya.

### ISSUE THREAD

**Issue by yohang88** [jabardigitalservice/pikobar-jabarprov-go-id#102]
Seharusnya jika posting/share URL di sosial media (facebook), muncul judul berita dan excerpt (potongan) contentnya. Saat ini yang muncul adalah judul website PIKOBAR.

![image](https://user-images.githubusercontent.com/618412/78685959-aa370880-791c-11ea-8fdf-d2aca301c2d3.png)

**Comment by adrianpdm** [comment]
artikel yang baru ditambahkan **setelah** web di deploy tidak akan memiliki dedicated meta tags mas @yohang88 . sempat disinggung pada PR #37.

jika dedicated meta tags  menjadi requirement, perlu dibuat trigger dari firebase, agar netlify melakukan pre-render (deploy) ulang setiap kali ada document baru di /articles atau /infographics.

**Comment by adrianpdm** [comment]
boleh di cek disini:
https://developers.facebook.com/tools/debug/

Item yang di-submit ke firestore **sebelum** deploy (punya meta tags):
https://pikobar.jabarprov.go.id/articles/gubernur-jabar-ridwan-kamil-resmikan-rsud-via-video-conference-rsud-pandega-pangandaran-sediakan-enam-ruang-isolasi-covid-19-artcl.k8n61r50m60hj8p587k/

Item yang di-submit ke firestore setelah deployed (tidak punya meta tags):
https://pikobar.jabarprov.go.id/articles/tampung-di-hotel-bintang-lima-gubernur-jabar-sambangi-tenaga-medis-perawat-pasien-covid-19-artcl.k8ps736vovksqluemsw

**Comment by adrianpdm** [comment]
![image](https://user-images.githubusercontent.com/20709202/78745870-9c6e9b00-798f-11ea-8a8d-e2e15432d161.png)
