### ISSUE TITLE
Ditambahkan menu/link/section untuk ke Dashboard Nasional COVID-19

### ISSUE THREAD

**Issue by yohang88** [jabardigitalservice/pikobar-jabarprov-go-id#103]
Kalau di aplikasi mobile, untuk menu Data Nasional akan menampilkan: https://experience.arcgis.com/experience/57237ebe9c5b4b1caa1b93e79c920338

Nice to have jika bisa pakai `remote configurable`.

**Comment by adrianpdm** [comment]
cc: @adtrimurdani @syarifhida

**Comment by adtrimurdani** [comment]
wait mas @yohang88 sy coba atur2 dulu layoutnya ya
