### ISSUE TITLE
Menambahkan separator pada angka ribuan

### ISSUE THREAD

**Issue by adtrimurdani** [jabardigitalservice/pikobar-jabarprov-go-id#106]
Pada angka-angka di `Pertanyaan Terlayani`dan pada tab `Statistik`, ditampilkan dengan separator ribuan. Format lokal Indonesia pakai titik.
![image](https://user-images.githubusercontent.com/61811037/78781912-4b7c9800-79cb-11ea-9267-e5e0ac98597f.png)

**Comment by adrianpdm** [comment]
thousand separator menggunakan `.` (titik)
decimal separator menggunakan `,` (koma)

resolved on #108

**Comment by adrianpdm** [comment]
kang @akatgelar @yunusffz 
untuk di halaman dashboard boleh diformat juga menggunakan helper di `~/lib/number.js`
