### ISSUE TITLE
Backlink pada judul Berita Nasional dan Dunia redirect ke halaman article nya

### ISSUE THREAD

**Issue by adtrimurdani** [jabardigitalservice/pikobar-jabarprov-go-id#115]
Saat ini backlink pada judul masih seperti di bawah:
![image](https://user-images.githubusercontent.com/61811037/78976089-ad5e0e80-7b3f-11ea-821f-fec93f59ed68.png)

**Comment by adrianpdm** [comment]
resolve on #116
