### ISSUE TITLE
Fix redaksional pada beberapa section

### ISSUE THREAD

**Issue by adtrimurdani** [jabardigitalservice/pikobar-jabarprov-go-id#121]
Pada section `Punya Pertanyaan Terkait COVID-19` wording nya direvisi jadi:
Tanya kepada sesama wargi Jabar soal penanganan COVID-19 di Forum Pikobar!

Pada judul section `Ketahui Resiko dari COVID-19` menjadi: Ketahui Risiko dari COVID-19

**Comment by TendiF** [comment]
boleh di assign ke saya aja pak

**Comment by adtrimurdani** [comment]
boleh kang @TendiF , terima kasih ya🙏
