### ISSUE TITLE
Tambahan partner di footer: Geocreate

### ISSUE THREAD

**Issue by adtrimurdani** [jabardigitalservice/pikobar-jabarprov-go-id#125]
Logo: 
![image](https://user-images.githubusercontent.com/61811037/79189826-f7e7cf80-7e4c-11ea-8b01-9b4215f714b5.png)

Backlink: https://www.linkedin.com/company/geospatial-creative-institute/

**Comment by TendiF** [comment]
boleh di assign ke saya aja pak

**Comment by adtrimurdani** [comment]
boleh kang @TendiF , terima kasih 🙏
