### ISSUE TITLE
Penambahan halaman baru: Donasi

### ISSUE THREAD

**Issue by adtrimurdani** [jabardigitalservice/pikobar-jabarprov-go-id#128]
File Wireframe: https://drive.google.com/drive/u/0/folders/13Hr2Yl14M4s0xYgQPNe7JnyaGmo98T9k

mas @syarifhida boleh mintol dibuatin design UI nya untuk ini?

**Comment by syarifhida** [comment]
ok kang, point prioritas berapa kang? ini dikejar untuk dashboard eksekutif juga soalnya

**Comment by adtrimurdani** [comment]
boleh setelah executive dashboard aja mas @syarifhida

**Comment by syarifhida** [comment]
ok kang @adtrimurdani

**Comment by adtrimurdani** [comment]
mas @syarifhida punteun, dari sana ada update utk yg di halaman utama nya: https://drive.google.com/file/d/1y5ymxbV9mpEDsGOei0eHmoCX752twndV/view?usp=sharing

**Comment by syarifhida** [comment]
Done kang

**Comment by adtrimurdani** [comment]
ntaps, nuhun mas @syarifhida
