### ISSUE TITLE
Ganti Nomor Dinkes menjadi Hotline Pikobar

### ISSUE THREAD

**Issue by adtrimurdani** [jabardigitalservice/pikobar-jabarprov-go-id#134]
![image](https://user-images.githubusercontent.com/61811037/79822505-80b9ba80-83bb-11ea-8a79-99218107247d.png)
Diganti menjadi:
### **Hotline Pikobar**
(Chat WA seputar COVID-19)
0811 1310 3515

- Lambang Telp ganti dengan lambang WA
- pas di klik, link nya ke sini: https://s.id/ChatbotPikobar

**Comment by adrianpdm** [comment]
ini langsung ke master ya

**Comment by adrianpdm** [comment]
resolve on #135

**Comment by adtrimurdani** [comment]
ini saya re-open lagi ya, ada pergantian nomor. Tapi kali ini nomor tidak usah di display, cukup keterangan aja:
**Hotline Pikobar**
Pertanyaan umum
(icon WA) Klik untuk chat

pas di klik, link nya tetep ke sini: https://s.id/ChatbotPikobar
