### ISSUE TITLE
Penambahan pop-up image berisi campaign/informasi seputar Penanganan COVID-19 Jabar

### ISSUE THREAD

**Issue by adtrimurdani** [jabardigitalservice/pikobar-jabarprov-go-id#204]
Konsepnya seperti In-App Messaging yang sudah diimplementasikan lebih dulu di app Pikobar, yaitu menampilkan pop-up image berisi campaign/informasi seputar penangnanan COVID-19 di Jabar
Contoh:
![image](https://user-images.githubusercontent.com/61811037/84344770-cfbee780-abd5-11ea-834f-4e30a961df9f.png)

**Comment by adrianpdm** [comment]
resolved on #208
