### ISSUE TITLE
Penggantian Section Pertanyaan Terlayani dengan Socmed Pikobar

### ISSUE THREAD

**Issue by adtrimurdani** [jabardigitalservice/pikobar-jabarprov-go-id#211]
Teks `Pertanyaan Terlayani` diganti dengan `Media Sosial Pikobar`
IG yg ditambahkan: pikobar_jabar, jabardigitalservice, humas_jabar
link prototype: https://www.figma.com/proto/f33nLuTttpNyJ3PKNuXaif/Untitled?node-id=0%3A1

**Comment by adrianpdm** [comment]
resolved on #225
