### ISSUE TITLE
Halaman untuk Kebijakan Privacy

### ISSUE THREAD

**Issue by adtrimurdani** [jabardigitalservice/pikobar-jabarprov-go-id#212]
Dibuatkan 1 halaman di-publish untuk publik, misal pikobar.jabarprov.go.id/privacy
UI nya cukup konten Kebijakan Privacy nya saja + header dan menu2 di atas
Data diambil di Remote Config (sudah dibuat di terms_conditions)

**Comment by adrianpdm** [comment]
resolved on #224
