### ISSUE TITLE
Update section Lindungi Diri dan Orang Lain

### ISSUE THREAD

**Issue by adtrimurdani** [jabardigitalservice/pikobar-jabarprov-go-id#233]
Update title Lindungi Diri dan Orang Lain menjadi **Tetap Waspada dengan AKB30**

Image: https://firebasestorage.googleapis.com/v0/b/jabarprov-covid19.appspot.com/o/public%2Fakb.jpeg?alt=media&token=6455e6ee-2edc-457e-ab73-d4ce2468ca19

konten ambil di sini di kolom `Narasi Web`: https://docs.google.com/document/d/1uqFo-q_vwRP4TU1M3vzEHDWeSsb3t0MUi6fOtbv8F-8/edit

**Comment by adrianpdm** [comment]
refer to #260
