### ISSUE TITLE
Penyamaan warna dan size font serta warna icon pada section Media Sosial

### ISSUE THREAD

**Issue by adtrimurdani** [jabardigitalservice/pikobar-jabarprov-go-id#248]
- Warna dan ukuran font disesuaikan dengan yg section di atasnya
- Warna icon juga diganti menjadi hijau sesuai section di atasnya 
![image](https://user-images.githubusercontent.com/61811037/89988183-56ad4080-dca9-11ea-82a6-5d641545b5a7.png)

**Comment by adrianpdm** [comment]
refer to #259
