### ISSUE TITLE
Penambahan Logo Partner (ISMKI)

### ISSUE THREAD

**Issue by adtrimurdani** [jabardigitalservice/pikobar-jabarprov-go-id#255]
Logo: https://firebasestorage.googleapis.com/v0/b/jabarprov-covid19.appspot.com/o/public%2FISMKI.png?alt=media&token=70e9a933-a82c-41f8-b101-edf303cf4eaf

Untuk UI, logo nya bisa disimpan di baris ke-2

**Comment by adrianpdm** [comment]
refer to #258
