### ISSUE TITLE
[PWA] Saat mode offline web belum bisa diakses

### ISSUE THREAD

**Issue by alvinindra** [jabardigitalservice/pikobar-jabarprov-go-id#281]
## Akses mode offline
![image](https://user-images.githubusercontent.com/30944414/99935611-9fd65b80-2d93-11eb-8eb6-dcc4cb85f770.png)
#### Diberitahukan bahwa konten bisa digunakan dalam mode offline tetapi saat dicoba masih belum bisa
![image](https://user-images.githubusercontent.com/30944414/99935498-64d42800-2d93-11eb-95e6-c964218421a4.png)

Permasalahannya terdapat pada service-worker nya yang belum diberikan _precache_ dan _route_ pada bagian image, css, font dan js.

Sehingga saat dilihat di cache storage, belum terdapat file yang tercache lokalnya.

![image](https://user-images.githubusercontent.com/30944414/99935735-f93e8a80-2d93-11eb-8ac2-f555d2cd48e1.png)

**Comment by adtrimurdani** [comment]
Terima kasih banyak atas temuannya yang dikirimkan @alvinindra di sini. 🙏🏼
