### ISSUE TITLE
Infografis bisa menyimpan file pdf juga

### ISSUE THREAD

**Issue by adtrimurdani** [jabardigitalservice/pikobar-jabarprov-go-id#38]
Jika pada halaman Infografis nya dibutuhkan preview, maka gunakan gambar di bawah ini saja:
![pdf-icon](https://user-images.githubusercontent.com/61811037/77610532-8c999480-6f55-11ea-8724-44e92e95e185.png)

**Comment by adrianpdm** [comment]
kang @adtrimurdani, untuk mobile apakah sudah support download / share file PDF?

**Comment by adtrimurdani** [comment]
utk App mobile sementara tidak download/share PDF dlu @adrianpdm

**Comment by yohang88** [comment]
Btw untuk file dokumen PDF, aku pecah saja ya.  Jadi PDF ini bukan masuk ke infografis. Akan ada section sendiri "Documents" seperti di mobile app.

Task terpisah: https://github.com/jabardigitalservice/pikobar-jabarprov-go-id/issues/100
