### ISSUE TITLE
API untuk berita Jabar

### ISSUE THREAD

**Issue by adtrimurdani** [jabardigitalservice/pikobar-jabarprov-go-id#4]
API dari Humas Jabar: http://humas.jabarprov.go.id/api/berita/jabar-tanggap

**Comment by yohang88** [comment]
Punten kang @adtrimurdani ini seperti masukan saya di Flutter yak 🙏  https://github.com/jabardigitalservice/pikobar-flutter/issues/61

**Comment by adtrimurdani** [comment]
ok noted kang @aldidoanta
