### ISSUE TITLE
Set up local environment

### ISSUE THREAD

**Issue by aldidoanta** [jabardigitalservice/pikobar-jabarprov-go-id#56]
Membuat script untuk import Firestore schema dan seed data.

Referensi https://github.com/jloosli/node-firestore-import-export

EDIT 200330: Mengganti pendekatan yang dipakai untuk setup local environment
EDIT 200331: Mengganti pendekatan yang dipakai untuk setup local environment

**Comment by aldidoanta** [comment]
Saat mencoba `emulator suite`, `firebase init` tetap harus dijalankan, dan tetap harus mempunyai referensi ke Firebase app.

Saat ini sedang mencoba
https://github.com/soumak77/firebase-mock

**Comment by aldidoanta** [comment]
Lanjut ke Plan B: membuat step-by-step tutorial membuat Firebase app untuk keperluan development. Firebase app dibuat menggunakan Google account individu.

**Comment by TendiF** [comment]
> Lanjut ke Plan B: membuat step-by-step tutorial membuat Firebase app untuk keperluan development. Firebase app dibuat menggunakan Google account individu.

ini masing2 orang bikin buat settingan Firebasenya ? atau nanti satu org yang bikin terus di share 
settingan envnya?

**Comment by aldidoanta** [comment]
@TendiF Iya kang, setiap orang bikin Firebase project sendiri-sendiri. Nanti saya perjelas di README

Untuk referensi Firestore collection, bisa dilihat di [Wiki ini](https://github.com/jabardigitalservice/pikobar-flutter/wiki/Firestore%20Collection%20Structure).

Saat ini saya lagi bikin script untuk populate seed data tanpa harus bikin manual di Firebase console.

**Comment by aldidoanta** [comment]
Untuk export/import data, jadinya akan menggunakan https://github.com/jloosli/node-firestore-import-export, sudah di-edit di issue description. WIP import collection yang diperlukan untuk repo ini.

**Comment by aldidoanta** [comment]
Kang @TendiF boleh review PR untuk issue ini ya :pray: https://github.com/jabardigitalservice/pikobar-jabarprov-go-id/pull/76
