### ISSUE TITLE
Credit sponsored by Netlify

### ISSUE THREAD

**Issue by yohang88** [jabardigitalservice/pikobar-jabarprov-go-id#60]
Fyi kita dapat full sponsor dari Netlify untuk project Pikobar ini https://www.netlify.com/blog/2020/03/22/coronavirus/covid-19-support/

Minta tolong ditambahkan banner atau logo yang intinya kita give credits/thanks to Netlify

Mas @adtrimurdani @adrianpdm

**Comment by adtrimurdani** [comment]
Siap mas akan di tarok di Footer. 
Selain Netlify akan ditambahkan juga Prixa.ai, Humas Jabar. Yang belum apalagi ya mas @yohang88 ?

**Comment by yohang88** [comment]
Mas @adtrimurdani list contributor / relawan tolong dilist aja sementara mas, yang tahu dulu.

**Comment by adtrimurdani** [comment]
Siip noted mas @yohang88 di masukkin ke design dulu yes

**Comment by adtrimurdani** [comment]
@adrianpdm mas @yohang88 FYI design sudah jadi ya

**Comment by adrianpdm** [comment]
resolved on #67
