### ISSUE TITLE
Section cek sebaran by Geotag

### ISSUE THREAD

**Issue by adtrimurdani** [jabardigitalservice/pikobar-jabarprov-go-id#68]
fitur cek sebaran dan deteksi RS rujukan by Geotag
Sebelum di Allow location nya:
![image](https://user-images.githubusercontent.com/61811037/77904208-5e49eb00-72ae-11ea-9100-e2f6f22b22ea.png)

Setelah di Allow location nya:
![image](https://user-images.githubusercontent.com/61811037/77904278-7f124080-72ae-11ea-8b87-f3f54468fe6d.png)

Note:
Detail ada di Figma ya. Untuk lokasi RS terdekat misal hasilnya lebih dari 1 dapat scroll aja paling, max layout ngikutin Jumlah Kasus Covid aja

**Comment by adrianpdm** [comment]
kang @adtrimurdani , data geotag setiap rumah sakit nya akan dimasukkan ke firebase kah?

**Comment by adtrimurdani** [comment]
klo mnurut sy sih iya @adrianpdm , gmn mnurut mas @yohang88 ?

**Comment by adtrimurdani** [comment]
mang @adrianpdm kita coba dlu pake solusi data geotag dimasukkin di setiap RS ya, biar bisa digas dulu utk fitur ini

**Comment by adrianpdm** [comment]
Saat ini API sedang diupdate oleh tim data untuk mendukung parameter `radius`, sebagaimana termaktub pada Figma.
