### ISSUE TITLE
Response penampilan data kasus jabar lambat

### ISSUE THREAD

**Issue by dhiemaz** [jabardigitalservice/pikobar-jabarprov-go-id#75]
Response menampilkan data kasus diwilayah jabar pada aplikasi lambat, apakah pada bagian ini menginvoke api (backend) ?

**Comment by adrianpdm** [comment]
> Response menampilkan data kasus diwilayah jabar pada aplikasi lambat, apakah pada bagian ini menginvoke api (backend) ?

Tampilan data yang dimaksud ada pada halaman apa ya?

Saat ini, data peta menggunakan 2 widget:
a) embedded frame dari Tableau, dan
b) leaflet JS dengan data yang diperoleh dari backend.

Selebihnya diambil dari Firebase.

**Comment by dhiemaz** [comment]
terlampir screen capture nya

![Screenshot_2020_0401_172557](https://user-images.githubusercontent.com/6150781/78127264-093cdf00-743e-11ea-8846-d3ec40e19346.png)

apakah ini menggunakan embedded frame dari Tableu atau dari backend menggunakan leafletJS? dan apakah memungkinkan atau sudah diimplementasikan menggunakan caching (bila dibackend)..?

**Comment by adrianpdm** [comment]
> terlampir screen capture nya
> 
> ![Screenshot_2020_0401_172557](https://user-images.githubusercontent.com/6150781/78127264-093cdf00-743e-11ea-8846-d3ec40e19346.png)
> 
> 1. Apakah ini menggunakan embedded frame dari Tableu atau dari backend menggunakan leafletJS? FYI, saya cek data muncul setelah (+-) 3-4 detik.
> 2. Apakah memungkinkan atau sudah diimplementasikan menggunakan caching (bila dibackend)..?

1) Untuk data ini mengambil dari Firebase. Tableau dan Leaflet digunakan untuk tampilan peta saja pak.
2) Untuk saat ini belum ada caching strategy terkait konsumsi API. Adapun untuk beberapa jenis data, sudah di-prerender berikut komponennya (misalnya berita, infografis). Untuk data angka kejadian sendiri tidak kami pre-render untuk mencegah tampilnya data yang _stale_ / sudah tidak _update_.

Adakah saran terkait kasus di atas pak @dhiemaz ?

cc: @yohang88 @aldidoanta @adtrimurdani

**Comment by yohang88** [comment]
Iya, confirmed ini halaman-halaman sering nge-freeze.

**Comment by dhiemaz** [comment]
@adrianpdm untuk yang menggunakan / hit API mungkin bisa digunakan cache strategy, paling tidak dilakukan cache per +- 5 menit, agar tidak selalu direct hit / query dari backend ke komponen belakangnya. 

Sebelum itu mungkin kita bisa draw arsitektur yang digunakan aplikasi ini, saya lihat ada ticket yang sudah dibuat related ke dokumentasi, dari desainnya kita baru kita dapat gambaran point point mana yang menjadi bottleneck untuk kita fine tune.

**Comment by akatgelar** [comment]
FYI halaman data udah diperbaiki sejak 13 april
sejak tanggal itu pasti sudah tidak pernah nge-freeze lagi
problem freeze itu ada di component map, sudah diperbaiki
walaupun masih akses API, tapi sudah dioptimasi jadi lebih cepat loadnya

https://github.com/jabardigitalservice/pikobar-jabarprov-go-id/commit/7227dc816ef9567c8e134d1ba592ecc84c944e63

*kalau dirasa udah solve / puas, bisa di close issue-nya

**Comment by dhiemaz** [comment]
Ok, terima kasih.. kita close dulu issuenya ya..
