### ISSUE TITLE
Penambahan Img pada section "Lindungi Diri dan Orang Lain"

### ISSUE THREAD

**Issue by adtrimurdani** [jabardigitalservice/pikobar-jabarprov-go-id#80]
berikut url img nya: https://firebasestorage.googleapis.com/v0/b/jabarprov-covid19.appspot.com/o/public%2Flindungi-diri.jpeg?alt=media&token=e407e115-c82a-4159-b247-6976caab8051

**Comment by adrianpdm** [comment]
resolve on #86
