### ISSUE TITLE
Revisi beberapa wording dan img di homepage

### ISSUE THREAD

**Issue by adtrimurdani** [jabardigitalservice/pikobar-jabarprov-go-id#84]
wording di bawah **Ketahui Resiko dari COVID-19**
yang asalnya:
Virus ini juga menyebar dengan sangat cepat karena bisa pindah dari orang ke orang bahkan sebelum orang tersebut tidak menunjukkan gejala.
menjadi:
Virus ini juga menyebar dengan sangat cepat karena bisa pindah dari orang ke orang bahkan sebelum orang tersebut menunjukkan gejala.

Di bawah **Kenapa harus Social Distancing (Jaga Jarak Sesama)?**
yang asalnya:
Social distancing akan mengurangi laju penularan dan mengizinkan pasien terinfeksi untuk ditangani hingga sembuh, seperti di grafik terlampir.
menjadi:
Social distancing akan mengurangi laju penularan dan memungkinkan pasien terinfeksi untuk ditangani hingga sembuh, seperti di grafik terlampir.
dan gambar diganti dengan ini:
https://firebasestorage.googleapis.com/v0/b/jabarprov-covid19.appspot.com/o/public%2Fflatten.jpeg?alt=media&token=3d989ffe-f369-4835-a232-7cf61686abd5

**Comment by adrianpdm** [comment]
resolve on #86
