### ISSUE TITLE
Menambahkan menu Forum

### ISSUE THREAD

**Issue by yohang88** [jabardigitalservice/pikobar-jabarprov-go-id#92]
Menambahkan link ke https://forum.pikobar.jabarprov.go.id/

Nice to have kalau bisa pakai Firebase Remote Config seperti pada Flutter.

**Comment by adrianpdm** [comment]
cc: @adtrimurdani @syarifhida

**Comment by adtrimurdani** [comment]
FYI, Forum sudah live, tombolnya `Tanyakan Sekarang` ada di halaman home mas @yohang88 
Pertanyaannya apakah url forum bisa diatur di remote config mang @adrianpdm ?

**Comment by adrianpdm** [comment]
> FYI, Forum sudah live, tombolnya `Tanyakan Sekarang` ada di halaman home mas @yohang88
> Pertanyaannya apakah url forum bisa diatur di remote config mang @adrianpdm ?

Di remote config sudah ada kang.

Saat ini kan forum hanya bisa diakses via Pikobar-Web melalui tombol "Tanyakan Sekarang", yang bisa jadi kurang noticable dari sisi user.

Pada halaman desktop, bisa saya tambahkan di navbar.  Namun, untuk viewport mobile bagaimana ya? Karena menu item di bawah itu sudah padat (maksimal 5 item)

**Comment by adrianpdm** [comment]
Termasuk penambahan menu/link ke Dashboard Nasional (issue #103 )

**Comment by adtrimurdani** [comment]
Sepertinya bisa diganti dengan hamburger menu, dan IMO penempatannya bisa di kanan atas (replace lonceng notif aja), karena menu pesan notifikasi sudah ada di bagian menu nya. @adrianpdm 

mas @syarifhida minta di-update ya UI utk mobile nya.

**Comment by adtrimurdani** [comment]
mas @syarifhida untuk hamburger menu udah jadikah? bisa diliat dimana ya?

**Comment by syarifhida** [comment]
belum kang @adtrimurdani karena kemarin masih bingung, isi dari hamburger menu jadinya apa aja ya?

**Comment by adtrimurdani** [comment]
Ini mas @syarifhida :
- Home
- Data
- Berita
- Kontak
- FAQ
- Forum
- Donasi

**Comment by syarifhida** [comment]
ok noted kang @adtrimurdani

**Comment by syarifhida** [comment]
Done, ada di page ini yes. 
[https://www.figma.com/file/RBr5lZdlLOWMPOMgyssD75/Web-Survey?node-id=1171%3A584](url)

**Comment by adtrimurdani** [comment]
siapp nuhun mas @syarifhida
