### ISSUE TITLE
Ditambahkan daftar website gugus tugas di Kab/Kota Jawa Barat

### ISSUE THREAD

**Issue by yohang88** [jabardigitalservice/pikobar-jabarprov-go-id#94]
Website khusus COVID-19 Jawa Barat https://pikobar.jabarprov.go.id/
List website COVID-19 Kota Kabupaten di Jawa Barat berdasarkan kode wilayah : 	

```		
KODE	NAMA KOTA  	       website	
3201	BOGOR			https://covid-19.bogorkab.go.id	
3202	SUKABUMI		http://www.pikokami.sukabumikab.go.id	
3203	CIANJUR			https://covid19.cianjurkab.go.id	
3204	BANDUNG		https://covid19.bandungkab.go.id	
3205	GARUT			https://covid19.garutkab.go.id/	
3206	TASIKMALAYA		https://sigesit119.tasikmalayakab.go.id	
3207	CIAMIS			https://pikcovid19.ciamiskab.go.id	
3208	KUNINGAN		http://covid19.kuningankab.go.id	
3209	CIREBON			https://covid19.cirebonkab.go.id	
3210	MAJALENGKA		https://covid19.majalengkakab.go.id	
3211	SUMEDANG		http://covid19.sumedangkab.go.id	
3212	INDRAMAYU		http://covid19.indramayukab.go.id/	
3213	SUBANG			https://covid19.subang.go.id	
3214	PURWAKARTA		https://covid19.purwakartakab.go.id	
3215	KARAWANG		https://covid19.karawangkab.go.id/	
3216	BEKASI			https://pikokabsi.bekasikab.go.id/	
3217	BANDUNG BARAT	https://covid19.bandungbaratkab.go.id/	sama dengan portal
3218	PANGANDARAN	https://covid19.pangandarankab.go.id	
3271	KOTA BOGOR		http://covid19.kotabogor.go.id	
3272	KOTA SUKABUMI	https://covid19.sukabumikota.go.id	
3273	KOTA BANDUNG	https://covid19.bandung.go.id	
3274	KOTA CIREBON	http://covid19.cirebonkota.go.id	
3275	KOTA BEKASI		https://corona.bekasikota.go.id/	
3276	KOTA DEPOK		https://ccc-19.depok.go.id	
3277	KOTA CIMAHI		https://covid19.cimahikota.go.id	
3278	KOTA TASIKMALAYA http://mikotas.tasikmalayakota.go.id	
3279	KOTA BANJAR		https://banjarkota.go.id/berita-banjar/update-data-covid-19-kota-banjar/
```

**Comment by adrianpdm** [comment]
ini dimasukkan ke halaman /kontak kah? cc @adtrimurdani

**Comment by adtrimurdani** [comment]
Iya, tapi dibuatkan lagi section baru, judulnya `Website Gugus Tugas Kota/Kabupaten Jawa Barat`

**Comment by adrianpdm** [comment]
Issue ini di-assign pada @Maaz ya.
Hatur nuhunn 😄

**Comment by maasdi** [comment]
@adrianpdm github saya di @maasdi.
Nantinya feature, ini perlu collection baru.
Namanya mungkin collection `gugus_tugas`, dengan field kode, nama_kota dengan data type semuanya string.

Untuk display-nya nanti akan di sort by kode.

Mohon input-nya kalau ada..

**Comment by maasdi** [comment]
Ada perubahan sedikit.

**Nama collection:** `task_forces`
| Field | Data Type |
| ------------- | ------------- |
| code  | String  |
| name  | String  |
| website | String |

**Comment by maasdi** [comment]
Kang @yohang88  @adrianpdm 

Versi web:
![task_force_web](https://user-images.githubusercontent.com/1782263/78617872-5fc97380-78ab-11ea-811a-b1e28be124c9.jpg)

Versi mobile/small device
![task_force_mobile](https://user-images.githubusercontent.com/1782263/78617882-67891800-78ab-11ea-8ebd-45530b45cde9.jpg)

**Comment by adrianpdm** [comment]
> Ada perubahan sedikit.
> 
> **Nama collection:** `task_forces`
> 
> Field	Data Type
> code	String
> name	String
> website	String

Terimakasih pak @maasdi :smile:. Secara data dan tampilan sudah sesuai pak.
PR-nya segera kita merge setelah script untuk meng-ekstrak collection firebasenya selesai (WIP)
