### ISSUE TITLE
Tambah tab Dokumen di Halaman Infografis

### ISSUE THREAD

**Issue by adtrimurdani** [jabardigitalservice/pikobar-jabarprov-go-id#95]
Sebagai user, saya bisa melihat daftar dokumen (PDF) dan download file tersebut.

Yang dibutuhkan/ditampilkan (bikin collection baru di Firestore):

Judul dokumen
Deskripsi dokumen
Link download file (kalau di-tap, aksinya adalah download).
Action share (share file, bukan share link) [nice to have]
Tanggal publish (sort by tanggal publish, paling baru paling atas).

Referensi: https://corona.jakarta.go.id/id/publikasi
Mintol update design ya mas @syarifhida , nuhuns

**Comment by syarifhida** [comment]
Done, mockup ada di figma

**Comment by adrianpdm** [comment]
duplicate of #100
please refer to above issue for further updates

closed
