### ISSUE TITLE
Penambahan halaman untuk hasil RDT

### ISSUE THREAD

**Issue by adtrimurdani** [jabardigitalservice/pikobar-jabarprov-go-id#99]
Spek:
- halaman dibuat terpisah, tidak usah ditampilkan di web Pikobar
- tidak terakses publik
- draft sudah di-share di WA

**Comment by adrianpdm** [comment]
ini assignee nya siapa ya kang @adtrimurdani ?

**Comment by adtrimurdani** [comment]
atau dibagi2 untuk dibantu relawan juga boleh @adrianpdm

**Comment by adrianpdm** [comment]
resolve on #93
